"""Regenerate k8s/day-06-mcp.yaml from server.py, fo_mock.py and test_client.py (Day 6 sources).

Since Day 8a, mcp-server runs from the image built from apps/mcp-server; this Day 6 bundle is
kept for fo-mock, the mcp-test Job and the history.

Run on the box after editing any of the .py files:  python3 build_manifest.py
"""
import pathlib

HERE = pathlib.Path(__file__).parent
PY_IMAGE = "python:3.12-slim"
MCP_PIN = "mcp==2.2.0"
SERVER_DEPS = [MCP_PIN, "psycopg[binary]==3.3.6", "requests==2.34.2"]


def block(path):
    text = (HERE / path).read_text()
    return "\n".join(("    " + line) if line else "" for line in text.rstrip("\n").split("\n"))


def pip_cmd(deps):
    args = ["python", "-m", "pip", "install", "--no-cache-dir", "--disable-pip-version-check",
            "--only-binary=:all:", "--quiet", "--target", "/deps"] + deps
    return "[" + ", ".join('"' + a + '"' for a in args) + "]"


POD_SECURITY = """      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault"""

CONTAINER_SECURITY = """          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]"""


def deps_init(deps):
    return f"""      initContainers:
        # Temporary until day 8 (custom image): install pinned libraries into an emptyDir.
        - name: deps
          image: {PY_IMAGE}
          command: {pip_cmd(deps)}
          env:
            - name: HOME
              value: /tmp
{CONTAINER_SECURITY}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: deps
              mountPath: /deps
            - name: tmp
              mountPath: /tmp"""


manifest = f"""# Day 6: MCP server + mock D365 FO OData service in si-lab.
# Regenerated by build_manifest.py. Apply with:
#   kubectl apply -f ~/ssi-platform/k8s/day-06-mcp.yaml
# All FO data in fo-mock is FAKE demo data. fo-mock has no auth and is cluster-internal only.
apiVersion: v1
kind: ConfigMap
metadata:
  name: fo-mock-code
  namespace: si-lab
  labels:
    app: fo-mock
data:
  fo_mock.py: |
{block("fo_mock.py")}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-code
  namespace: si-lab
  labels:
    app: mcp-server
data:
  server.py: |
{block("server.py")}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-test-code
  namespace: si-lab
  labels:
    app: mcp-test
data:
  test_client.py: |
{block("test_client.py")}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fo-mock
  namespace: si-lab
  labels:
    app: fo-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fo-mock
  template:
    metadata:
      labels:
        app: fo-mock
    spec:
{POD_SECURITY}
      containers:
        - name: fo-mock
          image: {PY_IMAGE}
          command: ["python", "/app/fo_mock.py"]
          env:
            - name: PORT
              value: "8080"
            - name: FO_DEFAULT_COMPANY
              value: usmf
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - name: http
              containerPort: 8080
{CONTAINER_SECURITY}
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 30
          volumeMounts:
            - name: code
              mountPath: /app
              readOnly: true
      volumes:
        - name: code
          configMap:
            name: fo-mock-code
---
apiVersion: v1
kind: Service
metadata:
  name: fo-mock
  namespace: si-lab
  labels:
    app: fo-mock
spec:
  type: ClusterIP
  selector:
    app: fo-mock
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: si-lab
  labels:
    app: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
{POD_SECURITY}
{deps_init(SERVER_DEPS)}
      containers:
        - name: mcp-server
          image: {PY_IMAGE}
          command: ["python", "/app/server.py"]
          env:
            - name: PORT
              value: "8000"
            - name: OLLAMA_URL
              value: "http://ollama.si-lab.svc.cluster.local:11434"
            - name: PG_DSN
              value: "host=pgvector.si-lab.svc.cluster.local port=5432 dbname=rag user=rag"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgvector-auth
                  key: POSTGRES_PASSWORD
            - name: FO_BASE_URL
              value: "http://fo-mock.si-lab.svc.cluster.local:8080"
            - name: PYTHONPATH
              value: /deps
            - name: HOME
              value: /tmp
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - name: http
              containerPort: 8000
{CONTAINER_SECURITY}
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: code
              mountPath: /app
              readOnly: true
            - name: deps
              mountPath: /deps
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: code
          configMap:
            name: mcp-server-code
        - name: deps
          emptyDir: {{}}
        - name: tmp
          emptyDir: {{}}
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: si-lab
  labels:
    app: mcp-server
spec:
  type: ClusterIP
  selector:
    app: mcp-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
# Only mcp-server may open connections to fo-mock.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fo-mock-allow-mcp-server
  namespace: si-lab
spec:
  podSelector:
    matchLabels:
      app: fo-mock
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: mcp-server
      ports:
        - protocol: TCP
          port: 8080
---
# mcp-server accepts connections only from pods in si-lab (Open WebUI, the test Job).
# kubectl port-forward still works: it enters the pod's own network namespace.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mcp-server-allow-si-lab
  namespace: si-lab
spec:
  podSelector:
    matchLabels:
      app: mcp-server
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector: {{}}
      ports:
        - protocol: TCP
          port: 8000
---
# One-shot smoke test. To re-run: kubectl -n si-lab delete job mcp-test, then apply again.
apiVersion: batch/v1
kind: Job
metadata:
  name: mcp-test
  namespace: si-lab
  labels:
    app: mcp-test
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: mcp-test
    spec:
      restartPolicy: Never
{POD_SECURITY}
{deps_init([MCP_PIN])}
      containers:
        - name: test
          image: {PY_IMAGE}
          command: ["python", "/app/test_client.py"]
          env:
            - name: MCP_URL
              value: "http://mcp-server.si-lab.svc.cluster.local:8000/mcp"
            - name: PYTHONPATH
              value: /deps
            - name: HOME
              value: /tmp
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
{CONTAINER_SECURITY}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: code
              mountPath: /app
              readOnly: true
            - name: deps
              mountPath: /deps
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: code
          configMap:
            name: mcp-test-code
        - name: deps
          emptyDir: {{}}
        - name: tmp
          emptyDir: {{}}
"""

PGVECTOR_POLICY = """# OPTIONAL (day 6): only mcp-server and rag-worker may connect to pgvector.
# kubectl exec into pgvector-0 and kubectl port-forward are not affected.
# Roll back with: kubectl -n si-lab delete networkpolicy pgvector-allow-clients
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pgvector-allow-clients
  namespace: si-lab
spec:
  podSelector:
    matchLabels:
      app: pgvector
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: mcp-server
        - podSelector:
            matchLabels:
              app: rag-worker
      ports:
        - protocol: TCP
          port: 5432
"""

K8S = HERE.parent / "k8s"
(K8S / "day-06-mcp.yaml").write_text(manifest)
(K8S / "day-06-netpol-pgvector.yaml").write_text(PGVECTOR_POLICY)
print("wrote k8s/day-06-mcp.yaml and k8s/day-06-netpol-pgvector.yaml")
