"""Builds k8s/day-07-prompt-guard.yaml from server.py and download.py."""
from pathlib import Path

import yaml

HERE = Path(__file__).parent
OUT = HERE.parent / "k8s" / "day-07-prompt-guard.yaml"

MODEL_ID = "meta-llama/Llama-Prompt-Guard-2-22M"
MODEL_DIR = "/cache/models/Llama-Prompt-Guard-2-22M"
DEPS_DIR = "/cache/deps-v1"
PIP_PKGS = [
    "torch==2.14.0+cpu",
    "transformers==5.17.0",
    "huggingface-hub==1.33.0",
    "tokenizers==0.23.2",
    "safetensors==0.8.0",
    "fastapi==0.141.1",
    "uvicorn==0.54.0",
]
NS = "si-lab"
LABELS = {"app": "prompt-guard"}
RESTRICTED = {
    "allowPrivilegeEscalation": False,
    "readOnlyRootFilesystem": True,
    "capabilities": {"drop": ["ALL"]},
}

deps_script = (
    f'set -e; D={DEPS_DIR}; '
    'if [ -f "$D/.complete" ]; then echo "deps cached in $D"; exit 0; fi; '
    'rm -rf "$D" /cache/.pip-tmp; mkdir -p /cache/.pip-tmp; '
    'python -m pip install --no-cache-dir --disable-pip-version-check --only-binary=:all: --quiet '
    '--target "$D" --extra-index-url https://download.pytorch.org/whl/cpu '
    + " ".join(PIP_PKGS)
    + '; rm -rf /cache/.pip-tmp; touch "$D/.complete"; echo "deps installed in $D"'
)

common_env = [
    {"name": "HOME", "value": "/tmp"},
    {"name": "PYTHONPATH", "value": DEPS_DIR},
    {"name": "PYTHONDONTWRITEBYTECODE", "value": "1"},
    {"name": "PYTHONUNBUFFERED", "value": "1"},
    {"name": "HF_HOME", "value": "/cache/hf"},
    {"name": "MODEL_ID", "value": MODEL_ID},
    {"name": "MODEL_DIR", "value": MODEL_DIR},
]

header = f"""# Day 7 part 2: Prompt Guard 2 classifier service in si-lab (CPU, on the lab host).
# Generated by prompt-guard/build_manifest.py from prompt-guard/server.py and download.py.
# Model: {MODEL_ID} (gated on Hugging Face, Llama 4 Community License).
#   Before applying: request access on the model page, then create the Secret hf-token
#   (see docs/day-07-observability-steps.md). The token is only used by the init container.
# Why CPU on the lab host: ollama holds the 4 GB NVIDIA laptop GPU (no time-slicing), the monitoring node
#   RAM is budgeted for observability, and the 22M model answers in tens of ms on a laptop CPU.
# First start installs ~1.2 GB of Python packages (torch CPU, transformers) and ~0.3 GB of model
#   into the prompt-guard-cache PVC (pip's temp dir is on the PVC too, not in /tmp); later restarts reuse the cache and run fully offline.
# To switch to the multilingual 86M model: change MODEL_ID and MODEL_DIR in build_manifest.py.
# Apply:
#   kubectl apply -f ~/ssi-platform/k8s/day-07-prompt-guard.yaml
"""

docs = [
    {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": "prompt-guard-code", "namespace": NS, "labels": LABELS},
        "data": {
            "server.py": (HERE / "server.py").read_text(),
            "download.py": (HERE / "download.py").read_text(),
        },
    },
    {
        "apiVersion": "v1",
        "kind": "PersistentVolumeClaim",
        "metadata": {"name": "prompt-guard-cache", "namespace": NS, "labels": LABELS},
        "spec": {
            "accessModes": ["ReadWriteOnce"],
            "storageClassName": "local-path",
            "resources": {"requests": {"storage": "3Gi"}},
        },
    },
    {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {"name": "prompt-guard", "namespace": NS, "labels": LABELS},
        "spec": {
            "replicas": 1,
            "strategy": {"type": "Recreate"},
            "selector": {"matchLabels": LABELS},
            "template": {
                "metadata": {"labels": LABELS},
                "spec": {
                    "nodeSelector": {"kubernetes.io/hostname": "gpu-node"},
                    "automountServiceAccountToken": False,
                    "enableServiceLinks": False,
                    "securityContext": {
                        "runAsNonRoot": True,
                        "runAsUser": 10001,
                        "runAsGroup": 10001,
                        "fsGroup": 10001,
                        "seccompProfile": {"type": "RuntimeDefault"},
                    },
                    "initContainers": [
                        {
                            "name": "deps",
                            "image": "python:3.12-slim",
                            "command": ["sh", "-c", deps_script],
                            "env": [{"name": "HOME", "value": "/tmp"}, {"name": "TMPDIR", "value": "/cache/.pip-tmp"}],
                            "securityContext": RESTRICTED,
                            "resources": {
                                "requests": {"cpu": "200m", "memory": "512Mi"},
                                "limits": {"memory": "1536Mi"},
                            },
                            "volumeMounts": [
                                {"name": "cache", "mountPath": "/cache"},
                                {"name": "tmp", "mountPath": "/tmp"},
                            ],
                        },
                        {
                            "name": "model",
                            "image": "python:3.12-slim",
                            "command": ["python", "/app/download.py"],
                            "env": common_env
                            + [
                                {
                                    "name": "HF_TOKEN",
                                    "valueFrom": {
                                        "secretKeyRef": {
                                            "name": "hf-token",
                                            "key": "token",
                                            "optional": True,
                                        }
                                    },
                                }
                            ],
                            "securityContext": RESTRICTED,
                            "resources": {
                                "requests": {"cpu": "100m", "memory": "128Mi"},
                                "limits": {"memory": "512Mi"},
                            },
                            "volumeMounts": [
                                {"name": "code", "mountPath": "/app", "readOnly": True},
                                {"name": "cache", "mountPath": "/cache"},
                                {"name": "tmp", "mountPath": "/tmp"},
                            ],
                        },
                    ],
                    "containers": [
                        {
                            "name": "prompt-guard",
                            "image": "python:3.12-slim",
                            "command": [
                                "python", "-m", "uvicorn", "server:app",
                                "--app-dir", "/app", "--host", "0.0.0.0", "--port", "8080",
                                "--no-access-log",
                            ],
                            "env": common_env
                            + [
                                {"name": "HF_HUB_OFFLINE", "value": "1"},
                                {"name": "TRANSFORMERS_OFFLINE", "value": "1"},
                                {"name": "OMP_NUM_THREADS", "value": "2"},
                                {"name": "TORCH_THREADS", "value": "2"},
                                {"name": "THRESHOLD", "value": "0.5"},
                            ],
                            "ports": [{"name": "http", "containerPort": 8080}],
                            "securityContext": RESTRICTED,
                            "resources": {
                                "requests": {"cpu": "100m", "memory": "384Mi"},
                                "limits": {"memory": "1Gi"},
                            },
                            "startupProbe": {
                                "httpGet": {"path": "/healthz", "port": 8080},
                                "periodSeconds": 5,
                                "failureThreshold": 36,
                            },
                            "readinessProbe": {
                                "httpGet": {"path": "/healthz", "port": 8080},
                                "periodSeconds": 10,
                            },
                            "livenessProbe": {
                                "httpGet": {"path": "/healthz", "port": 8080},
                                "periodSeconds": 30,
                            },
                            "volumeMounts": [
                                {"name": "code", "mountPath": "/app", "readOnly": True},
                                {"name": "cache", "mountPath": "/cache", "readOnly": True},
                                {"name": "tmp", "mountPath": "/tmp"},
                            ],
                        }
                    ],
                    "volumes": [
                        {"name": "code", "configMap": {"name": "prompt-guard-code"}},
                        {"name": "cache", "persistentVolumeClaim": {"claimName": "prompt-guard-cache"}},
                        {"name": "tmp", "emptyDir": {"sizeLimit": "256Mi"}},
                    ],
                },
            },
        },
    },
    {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {"name": "prompt-guard", "namespace": NS, "labels": LABELS},
        "spec": {
            "selector": LABELS,
            "ports": [{"name": "http", "port": 8080, "targetPort": "http"}],
        },
    },
    {
        "apiVersion": "networking.k8s.io/v1",
        "kind": "NetworkPolicy",
        "metadata": {"name": "prompt-guard-allow-si-lab", "namespace": NS, "labels": LABELS},
        "spec": {
            "podSelector": {"matchLabels": LABELS},
            "policyTypes": ["Ingress"],
            "ingress": [
                {
                    "from": [{"podSelector": {}}],
                    "ports": [{"port": 8080, "protocol": "TCP"}],
                }
            ],
        },
    },
]


class Dumper(yaml.SafeDumper):
    pass


def _str(dumper, data):
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


Dumper.add_representer(str, _str)

body = "---\n".join(yaml.dump(d, Dumper=Dumper, sort_keys=False, width=1000) for d in docs)
OUT.write_text(header + "---\n" + body)
print(f"wrote {OUT}")
